services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    container_name: schoolapi-sqlserver
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "14333:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolapi-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=SchoolDb;User Id=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mssql-data:
